
version: "3.9"
services:
  web:
    image: sai-web
    ports:
      - "9000:80"

    environment:
      - BASE_URL=http://localhost:9000
      - WEB_CLIENT_NAME=Contained Solid Auth Agent
      - OIDC_CLIENT_ID=http://localhost:9000/assets/id.jsonld
      - SRV_BASE=http://localhost:4000
      - DEFAULT_IDP=http://localhost:3000
      - ENCODED_DEFAULT_IDP=http%3A%2F%2Flocalhost%3A3000
